[package]
name = "file_saver_rust"
version = "0.1.0"
authors = ["Durante"]
edition = "2021"

[dependencies]
pyo3 = { version = "0.18", features = ["extension-module"] }
tokio = { version = "1", features = ["full"] }
futures = { version = "0.3" }

[lib]
name = "file_saver_rust"
crate-type = ["cdylib"]
path = "src/lib.rs"

[package.metadata.maturin]
bindings = "pyo3"